In [ ]:
%%capture
# Installs Unsloth, Xformers, and TRL - run this not above
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps "xformers<0.0.27" "trl<0.9.0" peft accelerate bitsandbytes huggingface_hub

SyntaxError: invalid syntax (3372052957.py, line 2)

In [7]:
# 1. Install Unsloth (The optimization library)
%%capture
!pip install "unsloth[colab-new] @ git+[https://github.com/unslothai/unsloth.git](https://github.com/unslothai/unsloth.git)"
!pip install --no-deps "xformers<0.0.27" "trl<0.9.0" peft accelerate bitsandbytes huggingface_hub

UsageError: Line magic function `%%capture` not found.

In [5]:
# 2. Login
from unsloth import FastLanguageModel
from huggingface_hub import login
import torch

# PASTE YOUR HUGGING FACE TOKEN HERE
# Get it here: [https://huggingface.co/settings/tokens](https://huggingface.co/settings/tokens)
hf_token = "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"

try:
    login(token=hf_token)
except:
    print("Login failed or token not provided yet.")

# 3. Verify Installation
try:
    import unsloth
    print("✅ Unsloth Installed Successfully")
except ImportError:
    print("❌ Unsloth installation failed. Please check the logs.")

ModuleNotFoundError: No module named 'unsloth'

In [3]:
# ==========================================
# CELL 2: LOAD 8B MODEL
# ==========================================
from unsloth import FastLanguageModel
import torch

max_seq_length = 4096
dtype = None
load_in_4bit = True

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 64,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

==((====))==  Unsloth 2025.12.8: Fast Llama patching. Transformers: 4.57.3.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/5.96G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

Unsloth 2025.12.8 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

In [4]:
# ==========================================
# CELL 3: LOAD YOUR CUSTOM DATASET
# ==========================================
from datasets import load_dataset
from unsloth.chat_templates import get_chat_template
import json
import ast

# 1. Setup Chat Template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)

def formatting_prompts_func(examples):
    convos = examples["messages"]
    texts = []
    for convo in convos:
        # --- FIX: Handle Stringified Lists ---
        # If 'convo' is a string (e.g. "[{'role':...}]"), parse it.
        if isinstance(convo, str):
            try:
                convo = json.loads(convo)
            except:
                try:
                    convo = ast.literal_eval(convo)
                except:
                    pass # Keep as is if parsing fails

        # --- FIX: Handle Stringified Dicts inside List ---
        # If 'convo' is a list of strings (e.g. ["{'role':...}"]), parse items.
        if isinstance(convo, list) and len(convo) > 0 and isinstance(convo[0], str):
            parsed_convo = []
            for msg in convo:
                if isinstance(msg, str):
                    try:
                        parsed_convo.append(json.loads(msg))
                    except:
                        try:
                            parsed_convo.append(ast.literal_eval(msg))
                        except:
                            parsed_convo.append(msg) # Fail safe
                else:
                    parsed_convo.append(msg)
            convo = parsed_convo

        # Apply Template
        try:
            text = tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False)
            texts.append(text)
        except Exception as e:
            # If a row is still broken, skip it or print error (prevents crash)
            # print(f"Skipping bad row: {e}")
            texts.append("")

    return { "text" : texts }

# 2. Load Dataset directly from Hugging Face
print("⏳ Downloading your dataset from hasinduOnline...")
dataset = load_dataset("hasinduOnline/akura-sinhala-dyslexia-dataset", split = "train")

# 3. Format the dataset
dataset = dataset.map(formatting_prompts_func, batched = True,)

print(f"✅ Dataset Loaded Successfully! Found {len(dataset)} examples.")
# Print first valid example to check
if len(dataset) > 0:
    print("Sample Input:", dataset[0]['text'])

⏳ Downloading your dataset from hasinduOnline...

README.md:   0%|          | 0.00/592 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/5.71M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/658k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20727 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2303 [00:00<?, ? examples/s]

Map:   0%|          | 0/20727 [00:00<?, ? examples/s]

✅ Dataset Loaded Successfully! Found 20727 examples.
Sample Input: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

You are Akura AI, an expert in correcting Sinhala text for individuals with dyslexia. You will receive potentially incorrect text and provide a corrected version, along with an analysis of the errors you identified and corrected.<|eot_id|><|start_header_id|>user<|end_header_id|>

ගාණට සල්ලි<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"correction": "ගානට සල්ලි", "analysis": [{"error": "Phonetic Confusion", "details": "Replaced 'ණ' with 'න'"}]}<|eot_id|>

In [ ]:
# ==========================================
# CELL 4: START TRAINING (OPTIMIZED FOR 23K ROWS)
# ==========================================
from trl import SFTTrainer
from transformers import TrainingArguments
import torch

# Calculate steps automatically based on dataset size
# 23,000 rows / (2 batch * 4 accum) ≈ 2,875 steps
num_epochs = 1

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = 2048,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,  # Effective batch size = 8
        num_train_epochs = num_epochs,    # CHANGED: Uses all 23,030 rows
        # max_steps = 100,                # REMOVED: This was limiting you

        warmup_ratio = 0.03,              # Smoothly ramps up learning (better than fixed 5 steps)
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),

        logging_steps = 50,               # Log every 50 steps (less noise)
        save_strategy = "epoch",          # Save the model only after the full epoch
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none",               # Prevents W&B login prompts if you don't use it
    ),
)

print(f"🚀 Starting Training on full dataset ({len(dataset)} rows)...")
trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.

🚀 Starting Training on full dataset (20727 rows)...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 20,727 | Num Epochs = 1 | Total steps = 2,591
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 167,772,160 of 8,198,033,408 (2.05% trained)

In [1]:
# ==========================================
# CELL 5: SAVE & TEST
# ==========================================
model.save_pretrained("akura_llama_8b_realworld")
tokenizer.save_pretrained("akura_llama_8b_realworld")

# Test
FastLanguageModel.for_inference(model)
messages = [{"role": "system", "content": "You are Akura AI."}, {"role": "user", "content": "මම ගෙරද යනව"}]
inputs = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")
outputs = model.generate(input_ids=inputs, max_new_tokens=256, use_cache=True)
print("\n--- Model Response ---")
print(tokenizer.batch_decode(outputs)[0])

NameError: name 'model' is not defined

In [ ]:
# ==========================================
# CELL 5: SAVE ENTIRE MERGED MODEL & DOWNLOAD
# ==========================================
from google.colab import files
import shutil

# 1. Merge LoRA adapters into the base model
# This creates a standalone model folder (~16GB) that needs no base model to run.
model_name = "akura_llama_8b_full"
print(f"💾 Merging and saving full model to {model_name}...")

# Use "merged_16bit" for highest quality or "merged_4bit" for smaller size
model.save_pretrained_merged(model_name, tokenizer, save_method = "merged_16bit")

# 2. Test Inference (Optional)
FastLanguageModel.for_inference(model)
messages = [{"role": "system", "content": "You are Akura AI."}, {"role": "user", "content": "මම ගෙරද යනව"}]
inputs = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")
outputs = model.generate(input_ids=inputs, max_new_tokens=256, use_cache=True)
print("\n--- Model Response ---")
print(tokenizer.batch_decode(outputs)[0])

# 3. Zip the folder
# Warning: The zip file will be large (~15-16GB). Ensure you have stable internet.
print("📦 Zipping model folder...")
shutil.make_archive(model_name, 'zip', model_name)

# 4. Trigger Browser Download
print("⬇️ Downloading zip file...")
files.download(f"{model_name}.zip")

💾 Merging and saving full model to akura_llama_8b_full...

NameError: name 'model' is not defined